DROP TABLE IF EXISTS NAVYUG_USERS ;
  
CREATE TABLE NAVYUG_USERS (
  account_id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  city VARCHAR(250) NOT NULL,
  phone VARCHAR(250) DEFAULT NULL,
  balance DOUBLE DEFAULT 0 ,
  account_type VARCHAR(250)
);


